numpy is extremely used in the scientic computing and is also faster and convinient to use rather than lists 

3 main benefits are :
* less memory
* faster
* convinient
we can use numpy to create array of various sizes and perform some faster operations on the arrays

we will directly examine these three properties practically through codes 


In [2]:
import numpy as np
import time 
import sys

#lets have a list 

l = range(10000)
print('memory of lists:',sys.getsizeof(l[9])*len(l)) # gets the size of some random element of the list * len of list

a = np.arange(10000)
print('memory numpy array:',a.size*a.itemsize)


# u can see that memory occupied is also less compared to the list almost 7 times lesser memory
# consumed by the numpy arrrays 
      

memory of lists: 280000
memory numpy array: 40000


* numpy : conitnuous memory allocation 
* list : pointer to each element but random memory locations 


In [3]:
#let compare their time by doing some operation on both list and numpy arrays 

import numpy as np
import time 
import sys

size = 10000000

list_1 = range(size)
list_2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(list_1,list_2)]
print("python list  took",time.time()-start)

start = time.time()
result = a1+a2
print('numpy took',time.time()-start)


python list  took 2.3566348552703857
numpy took 0.2593057155609131


In [4]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

# basic arithmatic automation

print(a1*a2)
print(a1+a2)
print(a1/a2)
print(a1-a2)

[ 4 10 18]
[5 7 9]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [5]:
import numpy as np
a = np.array([1,2,3])



In [6]:
a[2]

3

In [7]:
a1 = np.array([[1,2,3,4,5],[4,5,6,4,5]])

In [8]:
a1.ndim

2

In [9]:
a1.shape

(2, 5)

In [10]:
a2 = np.array([[1,2],[3,4]])
a2.ndim

2

In [12]:
a2.itemsize

4

In [13]:
a.dtype


dtype('int32')

In [14]:
a = np.array([[1,2],[3,4]],dtype = np.float64)

In [15]:
a.dtype

dtype('float64')

In [16]:
a.itemsize

8

In [17]:
a.size

4

In [18]:
a2.size

4

In [19]:
a2

array([[1, 2],
       [3, 4]])

In [20]:
a

array([[1., 2.],
       [3., 4.]])

In [21]:
a.shape

(2, 2)

In [24]:
a = np.array([[1,2],[3,4]],dtype = complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [26]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
l = range(0,5)

In [31]:
l[2]

2

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [34]:
np.arange(1, 10,2)

array([1, 3, 5, 7, 9])

In [45]:
np.linspace(1 , 10 ,4)

array([ 1.,  4.,  7., 10.])

In [46]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [47]:
a.reshape(4,1)   # do not alter the original array

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j]])

In [49]:
a.ravel()  # do not alter the original array

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [50]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [51]:
a.min()

(1+0j)

In [52]:
a.max()

(4+0j)

In [53]:
a.sum()

(10+0j)

In [ ]:
axis 0 is columns (sum of columns)
axis 1 is rows (sum of rows )



In [54]:
a.sum(axis=0)

array([4.+0.j, 6.+0.j])

In [55]:
a.sum(axis=1)

array([3.+0.j, 7.+0.j])

In [56]:
 a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [57]:
a2

array([[1, 2],
       [3, 4]])

In [58]:
np.sqrt(a2)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [59]:
np.std(a2)

1.118033988749895

In [60]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


In [61]:
a

array([[1, 2],
       [3, 4]])

In [62]:
b

array([[5, 6],
       [7, 8]])

In [63]:
a+b

array([[ 6,  8],
       [10, 12]])

In [64]:
a.dot(b)  # matrix product 

array([[19, 22],
       [43, 50]])

In [65]:

a


array([[1, 2],
       [3, 4]])

In [67]:
b = np.arange(30).reshape(2,15)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [69]:
np.hsplit(b,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [76]:
b = b.reshape(5,6)
b


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [77]:
np.hsplit(b,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29]])]

In [81]:
np.vsplit(b,5)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]])]

In [82]:
a

array([[1, 2],
       [3, 4]])

In [90]:

c = np.arange(10).reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
np.vstack((a,c))

array([[1, 2],
       [3, 4],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
np.hstack((a,a))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])