In [3]:
import numpy as np
import time 
import sys

l = range(1000)
print(len(l))
print(sys.getsizeof(5))
print(sys.getsizeof(5)*len(l))

array = np.arange(1000)
print(array.size*array.itemsize)

1000
28
28000
8000


In [4]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [5]:
a2-a1

array([3, 3, 3])

In [6]:
import numpy as np
a = np.array([[1,2],[3,4],[5,4]])
a

array([[1, 2],
       [3, 4],
       [5, 4]])

In [7]:
a.ndim

2

In [8]:
a.size

6

In [9]:
a.itemsize

8

In [10]:
a.dtype

dtype('int64')

In [11]:
a = np.array([[1,2],[3,4],[5,4]],dtype=np.float64)
a.itemsize

8

In [12]:
a

array([[1., 2.],
       [3., 4.],
       [5., 4.]])

In [13]:
a.shape

(3, 2)

In [14]:
3X2 matrix

SyntaxError: invalid decimal literal (4253573225.py, line 1)

In [36]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
l = range(5)


In [39]:
l

range(0, 5)

In [42]:
np.arange(1,5)

array([1, 2, 3, 4])

In [43]:
np.arange(1,10,3)

array([1, 4, 7])

In [49]:
np.linspace(1,4,10)     # start , end , size of division


array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [50]:
a.shape

(3, 2)

In [52]:
a.reshape(3,2)

array([[1., 2.],
       [3., 4.],
       [5., 4.]])

In [53]:
a.reshape(6,1)


array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [4.]])

In [55]:
a.ravel()


array([1., 2., 3., 4., 5., 4.])

In [56]:
a  # original still the same not affected

array([[1., 2.],
       [3., 4.],
       [5., 4.]])

In [58]:
a.sum()

np.float64(19.0)

In [59]:
a.min()

np.float64(1.0)

In [60]:
a.max()

np.float64(5.0)

In [62]:
a.sum(axis=0)    # axis 0 = column pointer   axis 1 = row pointer 

array([ 9., 10.])

In [65]:
np.sqrt(a)     


array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.        ]])

In [66]:
np.std(a)

np.float64(1.3437096247164249)

In [67]:
h = np.array([[1,2],[4,5],[6,7]])

In [68]:
h

array([[1, 2],
       [4, 5],
       [6, 7]])

In [69]:
i = np.array([[3,4],[3,2],[1,2]])
i

array([[3, 4],
       [3, 2],
       [1, 2]])

In [70]:
h+i

array([[4, 6],
       [7, 7],
       [7, 9]])

In [ ]:
slicing and stacking 


In [71]:
#indexing
n= [2,3,4]



In [72]:
n[0:2]

[2, 3]

In [73]:
n[-1]

4

In [74]:
a=np.array([6,3,4])

In [75]:
a[0:2]

array([6, 3])

In [76]:
a[-1]

np.int64(4)

In [77]:
 a = np.array([[4,5,6],[6,7,8],[8,7,8]])

In [78]:
a


array([[4, 5, 6],
       [6, 7, 8],
       [8, 7, 8]])

In [82]:
a[1,2]

np.int64(8)

In [83]:
a[1:2]

array([[6, 7, 8]])

In [86]:
a[0:3,1]

array([5, 7, 7])

In [87]:
a[-1]

array([8, 7, 8])

In [88]:
a[-1,2]

np.int64(8)

In [91]:
a[0:3]

array([[4, 5, 6],
       [6, 7, 8],
       [8, 7, 8]])

In [97]:
a[0:3,0:2]

array([[4, 5],
       [6, 7],
       [8, 7]])

In [99]:
a[:,0:2]

array([[4, 5],
       [6, 7],
       [8, 7]])

In [103]:
c = np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [1]:
result=np.hsplit(c,5)

NameError: name 'np' is not defined

In [2]:
result

NameError: name 'result' is not defined

In [109]:
result[0]

array([[ 0,  1,  2],
       [15, 16, 17]])

In [113]:
result = np.vsplit(c,2)

In [114]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [115]:
b = np.arange(12).reshape(4,3)

In [116]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [117]:
l = b>3

In [118]:
l

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [121]:
b[l]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [122]:
b[l]=-1

In [123]:
b

array([[ 0,  1,  2],
       [ 3, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
# iteration through numpyrray 

